#!bin/sh
module="scull"
device="scull"
mode="664"
modules_dir=.
# 装载模块
/sbin/insmod ${modules_dir}/$module.ko $* || exit 1 

# 删除原有节点
rm -f /dev/${device}[0-3]

#从/proc/devices中获取主设备号，并在/dev目录中创建设备文件
major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
